# Name of SQL database
database_name: 'transition'

# Simulation Parameters
simulation:
  # number of simulations
  num_sims: 50
  # number of years in each simulation
  years: 100
  # number of steps in each year
  steps: 4
  # start year (transient data cut-off)
  start: 50
  # transition run
  transition: true
  # transition years 
  transition_years: 1

# Market Parameters
market:
  # number of C-firms
  num_cfirms: 200
  # number of K-firms
  num_kfirms: 50
  # number of households
  num_households: 2000
  # number of banks
  num_banks: 10
  # proabability of deafault max data set length
  length: 500

# Bank Parameters
bank:
  # annual deposit interest
  deposit_interest: 0.001
  # annual loan interest initial value
  loan_interest: 0.02
  # annual loan interest standard deviation
  sigma: 0.03
  # annual speed of adjustment
  adjust: 0.1
  # number of years to repay loan
  loan_years: 10
  # desired capital ratio intercept
  capital_intercept: 0.06
  # desired capital ratio slope (1 - intercept)
  capital_slope: 1

# Firm Parameters
firm:
  # demand adaption
  adapt: 0.1
  # speed of adjustment (prices & wages)
  adjust: 0.1
  # annual labour productivity average growth rate
  growth: 0.02
  # annual labour productivity standard deviation
  sigma: 0.03
  # annual price standard deviation
  sigma_p: 0.03
  # annual wage standard deviation
  sigma_w: 0.03
  # annual capital depreciation rate
  depreciation: 0.1
  # number of banks visited (credit market)
  num_banks: 2
  # initial labour productivity
  productivity: 1
  # initial price
  price: 1

# Capital Firm Parameters
kfirm:
  # desired ratio of excess output
  excess_output: 0.1

# Consumption Firm Parameters
cfirm:
  # capital acceleration
  acceleration: 3
  # desired debt parameters
  d0: 0.5
  d1: 2
  d2: 1
  # number of K-firms visited (capital market)
  num_kfirms: 2

# Household Parameters
household:
  # marginal propensity to consume out of deposits
  mpc_deposits: 0.1
  # number of firms visited (labour market)
  num_firms: 4
  # number of C-firms visited (consumption market)
  num_cfirms: 2